### ISSUE TITLE
Couldn't load plugin.

### ISSUE THREAD

**Issue by chernyshof** [Kagami/mpv.js#14]
I'm trying to run example, but react can't render Player component. It's just say "Couldn't load plugin."
Any ideas how to fix this?

**Comment by itshaadi** [comment]
same problem on windows 10 just followed example instruction but didn't work.

**Comment by jonywtf** [comment]
on macos 10.12.6 i can see in terminal:
```
FIXME: missed GL function glBufferSubData
failed to initialize mpv GL context
```

**Comment by Kagami** [comment]
This is fixed in git, I need to make a new release of prebuilt binaries.

**Comment by jonywtf** [comment]
Thanks! I will try to rebuild from git!

**Comment by Kagami** [comment]
Please try with latest 0.2.2 release.

**Comment by Kagami** [comment]
Hope it was fixed.

**Comment by itshaadi** [comment]
on windows you should put the corresponding `mpv-1.dll` next to `mpvjs.node`. i.e.

lets say you have a build process setup and after the build has finished, your `app` folder contains the full, runnable application.

``` bash
app:
│   app.html
│   main.js
│   renderer.js
└───mpv
        mpv-1.dll
        mpvjs.node
```

and in `main.js` add this line `const pluginDir = path.join(__dirname, 'mpv')` instead of `const pluginDir = path.join(path.dirname(require.resolve("mpv.js")), "build", "Release")`
