### ISSUE TITLE
Impossible to run it on systems without OpenGL (without video drivers)

### ISSUE THREAD

**Issue by peter23** [Kagami/mpv.js#17]
In such cases plugin can not be loaded and message
`failed to initialize mpv GL context`
can be seen in the console.

This problem happens for example on virtual machines without guest OS tools installed.

I know that playing video through OpenGL is a really good way.
But I think also will be good to have some fallback option to run it on systems without OpenGL.

**Comment by Kagami** [comment]
It might be possible in some way (e.g. WebChimera.js approach) but the way mpv.js embeds into Chrome Content Shell uses OpenGL so it's required. It would be completely different project otherwise.

Some hypervisors provide 3D acceleration (e.g. VirtualBox), you may enable it for testing purposes. There is also option to install OpenGL software implementation into guest, e.g. macOS has it out of the box.
