### ISSUE TITLE
NaCl SDK was deprecated by new chrome version, has any plan tranfer from naci to WebAssembly?

### ISSUE THREAD

**Issue by xiedeacc** [Kagami/mpv.js#95]
as title.
this a wonderful project, thanks

**Comment by Kagami** [comment]
Yeah, NaCl was already half-deprecated when I started this project, it might be already removed from current Chrome releases, haven't checked.
WASM version of MPV would be less performant because it can only access basic SSE instructions...
But it's probably the only future-proof way for this library.

**Comment by xiedeacc** [comment]
> Yeah, NaCl was already half-deprecated when I started this project, it might be already removed from current Chrome releases, haven't checked. WASM version of MPV would be less performant because it can only access basic SSE instructions... But it's probably the only future-proof way for this library.

I have an idea, a little tricky, add a IPC interface to mpv as a remote controller, then let mpv display under electron control

**Comment by Kagami** [comment]
Like [WebChimera's approach](https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues))? It's suboptimal too because of extra memcpy.
Better solution would be to somehow get OpenGL context of the Chrome's window (like described [here](https://github.com/RSATom/WebChimera.js/issues/116#issuecomment-279155414)) and draw directly on it from the mpv's shared library. But it might require patched Chrome so upstream electron won't work.

**Comment by xiedeacc** [comment]
> Like [WebChimera's approach](https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues))? It's suboptimal too because of extra memcpy. Better solution would be to somehow get OpenGL context of the Chrome's window (like described [here](https://github.com/RSATom/WebChimera.js/issues/116#issuecomment-279155414)) and draw directly on it from the mpv's shared library. But it might require patched Chrome so upstream electron won't work.

not same as webchimera, video was played by mpv with my solution, electron only send command, eg. control mpv to open a video file, send seek info to mpv. control mpv display position and size.  of couse, this solution cannot draw extra to mpv, anyway if anyone has need to draw on mpv, why not modify mpv

**Comment by Kagami** [comment]
> this solution cannot draw extra to mpv
> if anyone has need to draw on mpv, why not modify mpv

Because that's the main feature of electron? Easily create UI with HTML/CSS/JS.
Of course you can fork mpv and create your own video player in C but you don't need electron for that.
